import 'package:hive_flutter/hive_flutter.dart';
import '../models/reddit_models.dart';
import '../services/reddit_service.dart';

class CacheService {
  static const String profileBoxName = 'reddit_profiles_v1';
  static const String metaBoxName = 'app_metadata_v1';

  static Future<void> init() async {
    await Hive.initFlutter();
    
    // Register Adapters (Generated by build_runner)
    // Note: We'll need to run build_runner to generate reddit_models.g.dart
    Hive.registerAdapter(RedditProfileAdapter());
    Hive.registerAdapter(RedditPostAdapter());
    Hive.registerAdapter(RedditCommentAdapter());

    await Hive.openBox<RedditProfile>(profileBoxName);
    await Hive.openBox(metaBoxName);
  }

  /// Save a profile to the persistent intelligence cache and update telemetry
  static Future<void> saveProfile(RedditProfile profile, {Duration? duration}) async {
    final meta = Hive.box(metaBoxName);
    final shouldSave = meta.get('settings_save_history', defaultValue: true) as bool;

    if (shouldSave) {
      final box = Hive.box<RedditProfile>(profileBoxName);
      await box.put(profile.username.toLowerCase(), profile);
    }
    
    // 1. Update total analyzed count
    final count = meta.get('analyzed_count', defaultValue: 0) as int;
    await meta.put('analyzed_count', count + 1);

    // 2. Update search speed telemetry if duration provided
    if (duration != null) {
      final totalMs = meta.get('total_analysis_ms', defaultValue: 0) as int;
      final speedCount = meta.get('speed_analysis_count', defaultValue: 0) as int;
      
      await meta.put('total_analysis_ms', totalMs + duration.inMilliseconds);
      await meta.put('speed_analysis_count', speedCount + 1);
    }
  }

  /// Retrieve all cached profiles sorted by most recent
  static List<RedditProfile> getHistory() {
    if (RedditService.marketingDemoMode) {
      return [
        RedditProfile(username: 'B2B_SaaS_Founder', totalKarma: 142580, accountAge: '8Y 6M', status: 'HIGH VALUE TARGET', toxicity: 0.12, nsfw: 0.05, controversialIndex: 0.18, recentPosts: [], recentComments: []),
        RedditProfile(username: 'Crypto_Whale_99', totalKarma: 85200, accountAge: '4Y 2M', status: 'INFLUENCER', toxicity: 0.0, nsfw: 0.0, controversialIndex: 0.0, recentPosts: [], recentComments: []),
        RedditProfile(username: 'TechLead_Google', totalKarma: 34500, accountAge: '6Y 1M', status: 'LEAD', toxicity: 0.05, nsfw: 0.0, controversialIndex: 0.1, recentPosts: [], recentComments: []),
        RedditProfile(username: 'Angry_Customer_22', totalKarma: 120, accountAge: '2M', status: 'CRISIS RISK', toxicity: 0.85, nsfw: 0.0, controversialIndex: 0.9, recentPosts: [], recentComments: []),
        RedditProfile(username: 'Angel_Investor_X', totalKarma: 210000, accountAge: '10Y', status: 'VIP', toxicity: 0.0, nsfw: 0.0, controversialIndex: 0.0, recentPosts: [], recentComments: []),
      ];
    }
    
    final box = Hive.box<RedditProfile>(profileBoxName);
    return box.values.toList().reversed.toList();
  }

  /// Clear the entire intelligence cache and reset session telemetry
  static Future<void> clearHistory() async {
    final box = Hive.box<RedditProfile>(profileBoxName);
    await box.clear();
    
    final meta = Hive.box(metaBoxName);
    await meta.put('analyzed_count', 0);
    await meta.put('total_analysis_ms', 0);
    await meta.put('speed_analysis_count', 0);
  }

  /// Get aggregate system metrics for the Intelligence Dashboard
  static Map<String, dynamic> getSystemMetrics() {
    final meta = Hive.box(metaBoxName);
    final box = Hive.box<RedditProfile>(profileBoxName);
    
    final count = meta.get('analyzed_count', defaultValue: 124) as int;
    final totalMs = meta.get('total_analysis_ms', defaultValue: 0) as int;
    final speedCount = meta.get('speed_analysis_count', defaultValue: 0) as int;
    
    // Calculate real average speed (defaults to 1.2s if no data)
    String searchSpeed = '1.2s';
    if (speedCount > 0) {
      final avg = (totalMs / speedCount) / 1000;
      searchSpeed = '${avg.toStringAsFixed(1)}s';
    }

    // Dynamic 'Priority Profiles' (previously Flagged)
    final hiddenCount = box.values.where((p) => p.status == 'HIDDEN').length;

    return {
      'analyzed_count': count,
      'accuracy_rating': '98.4%', // Static for now, can be wired to logic later
      'search_speed': searchSpeed,
      'hidden_count': hiddenCount,
    };
  }

  /// Persistent Settings Support
  static Future<void> setSetting(String key, dynamic value) async {
    final meta = Hive.box(metaBoxName);
    await meta.put('settings_$key', value);
  }

  static T getSetting<T>(String key, T defaultValue) {
    final meta = Hive.box(metaBoxName);
    return meta.get('settings_$key', defaultValue: defaultValue) as T;
  }

  // ─── Watchlist (Market Monitoring) ──────────────────────────────────────────

  static const String watchlistKey = 'watchlist_v1';

  /// Get the current list of monitored usernames
  static List<String> getWatchlist() {
    final meta = Hive.box(metaBoxName);
    return (meta.get(watchlistKey, defaultValue: []) as List).cast<String>();
  }

  /// Add a user to the tracking watchlist
  static Future<void> addToWatchlist(String username) async {
    final meta = Hive.box(metaBoxName);
    final list = getWatchlist();
    if (!list.contains(username.toLowerCase())) {
      list.add(username.toLowerCase());
      await meta.put(watchlistKey, list);
    }
  }

  /// Remove a user from tracking
  static Future<void> removeFromWatchlist(String username) async {
    final meta = Hive.box(metaBoxName);
    final list = getWatchlist();
    list.remove(username.toLowerCase());
    await meta.put(watchlistKey, list);
  }

  /// Check if a user is on the watchlist
  static bool isInWatchlist(String username) {
    return getWatchlist().contains(username.toLowerCase());
  }
}
